"""新增消息通知表

Revision ID: 07211956930e
Revises: e8b48d3b44a9
Create Date: 2026-04-08 19:16:05.306391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07211956930e'
down_revision: Union[str, None] = 'e8b48d3b44a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.String(length=36), nullable=False, comment='通知id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('biz_type', sa.String(length=20), nullable=False, comment='业务类型'),
    sa.Column('biz_id', sa.String(length=36), nullable=True, comment='业务id(用于幂等性)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='负载(扩展数据，携带到跳转链接的参数)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'biz_type', 'biz_id', name='uix_user_id_biz_type_biz_id')
    )
    op.create_index('idx_user_id_created_at', 'notification', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id_read_at', 'notification', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notification_biz_id'), 'notification', ['biz_id'], unique=False)
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_biz_id'), table_name='notification')
    op.drop_index('idx_user_id_read_at', table_name='notification')
    op.drop_index('idx_user_id_created_at', table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
