"""调整 cover url 为一个对象

Revision ID: 098c6380dd8d
Revises: 83b310681c38
Create Date: 2025-11-21 19:34:44.442541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '098c6380dd8d'
down_revision: Union[str, None] = '83b310681c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'cover_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               comment='封面图信息',
               existing_comment='封面图',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'cover_url',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               comment='封面图',
               existing_comment='封面图信息',
               existing_nullable=True)
    # ### end Alembic commands ###
