"""同步最新的一些model

Revision ID: 0a8ce53073fd
Revises: 2dd360aa929c
Create Date: 2026-01-15 10:16:58.679820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a8ce53073fd'
down_revision: Union[str, None] = '2dd360aa929c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_view_history', 'user_id')
    op.drop_column('document_view_history', 'viewed_all_count_for_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_view_history', sa.Column('viewed_all_count_for_user', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户浏览了该文档的总次数'))
    op.add_column('document_view_history', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='浏览的用户'))
    # ### end Alembic commands ###
