"""同步role字段类型

Revision ID: 15b23446847b
Revises: 9c74ee41b8ab
Create Date: 2026-01-04 15:39:15.064927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15b23446847b'
down_revision: Union[str, None] = '9c74ee41b8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_collaborator', 'role',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_comment='角色',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_collaborator', 'role',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_comment='角色',
               existing_nullable=False)
    # ### end Alembic commands ###
