"""User表添加deletd_at字段

Revision ID: 25318514dd28
Revises: 7dc49ca1ce94
Create Date: 2026-01-14 14:36:18.161066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25318514dd28'
down_revision: Union[str, None] = '7dc49ca1ce94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_edit_history', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'document_view_history', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_constraint(None, 'document_view_history', type_='foreignkey')
    op.drop_constraint(None, 'document_edit_history', type_='foreignkey')
    # ### end Alembic commands ###
