"""外键还原

Revision ID: 2dd360aa929c
Revises: a5d2bbda09b7
Create Date: 2026-01-14 20:49:04.330648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd360aa929c'
down_revision: Union[str, None] = 'a5d2bbda09b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_node', 'knowledge_base', ['knowledge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_node', type_='foreignkey')
    # ### end Alembic commands ###
