"""调整知识库部分字段名

Revision ID: 2eba7055c978
Revises: 4b86730a8666
Create Date: 2026-01-09 14:56:13.316394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2eba7055c978'
down_revision: Union[str, None] = '4b86730a8666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('enable_custom_body', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否启用自定义模块'))
    op.add_column('knowledge_base', sa.Column('enable_user_feed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否显示协同人员'))
    op.drop_column('knowledge_base', 'enableUserFeed')
    op.drop_column('knowledge_base', 'enableCustomBody')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('enableCustomBody', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否启用自定义模块'))
    op.add_column('knowledge_base', sa.Column('enableUserFeed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否显示协同人员'))
    op.drop_column('knowledge_base', 'enable_user_feed')
    op.drop_column('knowledge_base', 'enable_custom_body')
    # ### end Alembic commands ###
