"""增加知识库关联关系

Revision ID: 3a938e67471c
Revises: f6a116a4b903
Create Date: 2025-11-19 10:52:04.405908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3a938e67471c"
down_revision: Union[str, None] = "f6a116a4b903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("knowledge_base_ibfk_1", "knowledge_base", type_="foreignkey")
    op.alter_column(
        "knowledge_group",
        "id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_comment="分组ID",
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_base",
        "group_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_comment="所属分组",
        existing_nullable=False,
    )
    op.create_foreign_key(
        None,
        "knowledge_base",
        "knowledge_group",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # 降级操作（反向顺序）
    op.drop_constraint(None, "knowledge_base", type_="foreignkey")
    op.alter_column(
        "knowledge_base",
        "group_id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_comment="所属分组",
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_group",
        "id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_comment="分组ID",
        existing_nullable=False,
    )
    op.create_foreign_key(
        "knowledge_base_ibfk_1",
        "knowledge_base",
        "knowledge_group",
        ["group_id"],
        ["id"],
    )
    # ### end Alembic commands ###
