"""新增机器人会话表,和消息表

Revision ID: 3f02410d5391
Revises: bda97ce03d8d
Create Date: 2026-03-24 20:03:21.708427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f02410d5391'
down_revision: Union[str, None] = 'bda97ce03d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.String(length=36), nullable=False, comment='会话id'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='用户id'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='会话状态'),
    sa.Column('last_message_preview', sa.String(length=100), nullable=True, comment='最后一条消息预览(通常用来做摘要)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_id'), 'chat_session', ['id'], unique=False)
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.String(length=36), nullable=False, comment='消息id'),
    sa.Column('session_id', sa.String(length=36), nullable=True, comment='会话id'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='消息类型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_id'), table_name='chat_session')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
