"""创建知识库分组中间表

Revision ID: 4528918fc7c5
Revises: 981f9480e6ef
Create Date: 2026-06-18 11:08:39.250295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4528918fc7c5'
down_revision: Union[str, None] = '981f9480e6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_group_relation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='排序索引'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['knowledge_group.id'], ),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'knowledge_id', name='uix_group_knowledge'),
    sa.UniqueConstraint('user_id', 'knowledge_id', name='uix_user_knowledge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_group_relation')
    # ### end Alembic commands ###
