"""node表字段同步

Revision ID: 45b6ed0a98f6
Revises: 25318514dd28
Create Date: 2026-01-14 20:40:29.523453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45b6ed0a98f6'
down_revision: Union[str, None] = '25318514dd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_node', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.alter_column('document_view_history', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='浏览的用户',
               existing_comment='所属用户',
               existing_nullable=False)
    op.drop_index(op.f('ix_document_view_history_viewed_all_count_for_user'), table_name='document_view_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_view_history_viewed_all_count_for_user'), 'document_view_history', ['viewed_all_count_for_user'], unique=False)
    op.alter_column('document_view_history', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='所属用户',
               existing_comment='浏览的用户',
               existing_nullable=False)
    op.drop_column('document_node', 'deleted_at')
    # ### end Alembic commands ###
