"""创建知识库日统计表,收藏表,更新一些表字段

Revision ID: 4b86730a8666
Revises: ff6a9c871364
Create Date: 2026-01-09 11:57:16.797469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b86730a8666'
down_revision: Union[str, None] = 'ff6a9c871364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('resource_type', sa.String(length=20), nullable=False, comment='资源类型'),
    sa.Column('knowledge_id', sa.String(length=36), nullable=True, comment='知识库ID'),
    sa.Column('document_id', sa.String(length=36), nullable=True, comment='文档ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_id', 'document_id', name='uix_user_knowledge_document')
    )
    op.create_index(op.f('ix_collect_document_id'), 'collect', ['document_id'], unique=False)
    op.create_index(op.f('ix_collect_knowledge_id'), 'collect', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_collect_user_id'), 'collect', ['user_id'], unique=False)
    op.add_column('knowledge_base', sa.Column('enable_catalog', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用目录'))
    op.add_column('knowledge_base', sa.Column('enableCustomBody', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否启用自定义模块'))
    op.add_column('knowledge_base', sa.Column('enableUserFeed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否显示协同人员'))
    op.add_column('knowledge_base', sa.Column('layout', sa.String(length=20), nullable=False, comment='布局'))
    op.add_column('knowledge_base', sa.Column('sort', sa.String(length=20), nullable=False, comment='排序'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base', 'sort')
    op.drop_column('knowledge_base', 'layout')
    op.drop_column('knowledge_base', 'enableUserFeed')
    op.drop_column('knowledge_base', 'enableCustomBody')
    op.drop_column('knowledge_base', 'enable_catalog')
    op.drop_index(op.f('ix_collect_user_id'), table_name='collect')
    op.drop_index(op.f('ix_collect_knowledge_id'), table_name='collect')
    op.drop_index(op.f('ix_collect_document_id'), table_name='collect')
    op.drop_table('collect')
    # ### end Alembic commands ###
