"""同步model

Revision ID: 56b658751814
Revises: b1714a76f3de
Create Date: 2025-12-05 10:17:34.599515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b658751814'
down_revision: Union[str, None] = 'b1714a76f3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_base',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('knowledge_id', sa.String(length=36), nullable=False, comment='所属知识库'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='文档名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='文档短链'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='文档类型'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否公开'),
    sa.Column('content_updated_at', sa.DateTime(), nullable=True, comment='内容最近更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_base_id'), 'document_base', ['id'], unique=False)
    op.create_index(op.f('ix_document_base_knowledge_id'), 'document_base', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_document_base_user_id'), 'document_base', ['user_id'], unique=False)
    op.create_table('document_content',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档'),
    sa.Column('content', sa.LargeBinary(), nullable=False, comment='文档内容(为协同编辑的的二进制数据)'),
    sa.Column('content_updated_at', sa.DateTime(), nullable=True, comment='内容最近更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_content_document_id'), 'document_content', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_content_id'), 'document_content', ['id'], unique=False)
    op.create_table('document_node',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='节点类型'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='节点标题'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父节点ID'),
    sa.Column('first_child_id', sa.String(length=36), nullable=True, comment='第一个子节点ID'),
    sa.Column('document_id', sa.String(length=36), nullable=True, comment='所属文档ID'),
    sa.Column('prev_id', sa.String(length=36), nullable=True, comment='前一个节点ID'),
    sa.Column('next_id', sa.String(length=36), nullable=True, comment='下一个节点ID'),
    sa.Column('knowledge_id', sa.String(length=36), nullable=True, comment='所属知识库ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_child_id'], ['document_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_id'], ['document_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prev_id'], ['document_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_node_document_id'), 'document_node', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_node_first_child_id'), 'document_node', ['first_child_id'], unique=False)
    op.create_index(op.f('ix_document_node_id'), 'document_node', ['id'], unique=False)
    op.create_index(op.f('ix_document_node_knowledge_id'), 'document_node', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_document_node_next_id'), 'document_node', ['next_id'], unique=False)
    op.create_index(op.f('ix_document_node_parent_id'), 'document_node', ['parent_id'], unique=False)
    op.create_index(op.f('ix_document_node_prev_id'), 'document_node', ['prev_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_node_prev_id'), table_name='document_node')
    op.drop_index(op.f('ix_document_node_parent_id'), table_name='document_node')
    op.drop_index(op.f('ix_document_node_next_id'), table_name='document_node')
    op.drop_index(op.f('ix_document_node_knowledge_id'), table_name='document_node')
    op.drop_index(op.f('ix_document_node_id'), table_name='document_node')
    op.drop_index(op.f('ix_document_node_first_child_id'), table_name='document_node')
    op.drop_index(op.f('ix_document_node_document_id'), table_name='document_node')
    op.drop_table('document_node')
    op.drop_index(op.f('ix_document_content_id'), table_name='document_content')
    op.drop_index(op.f('ix_document_content_document_id'), table_name='document_content')
    op.drop_table('document_content')
    op.drop_index(op.f('ix_document_base_user_id'), table_name='document_base')
    op.drop_index(op.f('ix_document_base_knowledge_id'), table_name='document_base')
    op.drop_index(op.f('ix_document_base_id'), table_name='document_base')
    op.drop_table('document_base')
    # ### end Alembic commands ###
