"""添加知识库公开密码配置,调整一些表字段

Revision ID: 5984b406803c
Revises: 7c28ef448f94
Create Date: 2026-07-03 20:09:07.469006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5984b406803c'
down_revision: Union[str, None] = '7c28ef448f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_access_setting',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('target_id', sa.String(length=36), nullable=False, comment='目标ID'),
    sa.Column('target_type', sa.String(length=30), nullable=False, comment='目标类型(knowledge, document)'),
    sa.Column('password', sa.String(length=4), nullable=False, comment='密码(这里为4位字符明文)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'target_type', name='uix_target_id_target_type')
    )
    op.create_index(op.f('ix_resource_access_setting_id'), 'resource_access_setting', ['id'], unique=False)
    op.drop_column('document_node', 'deleted_at')
    op.add_column('knowledge_base', sa.Column('enable_password_protection', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否启用高级密码保护,默认不开启'))
    op.drop_column('knowledge_group', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_group', sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.drop_column('knowledge_base', 'enable_password_protection')
    op.add_column('document_node', sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.drop_index(op.f('ix_resource_access_setting_id'), table_name='resource_access_setting')
    op.drop_table('resource_access_setting')
    # ### end Alembic commands ###
