"""增加空间表和团队表,调整知识库一些配置

Revision ID: 62018c92acf7
Revises: 9582d8948fec
Create Date: 2026-01-19 19:39:08.056199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62018c92acf7'
down_revision: Union[str, None] = '9582d8948fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'knowledge_base', 'space', ['space_id'], ['id'], ondelete='CASCADE')
    op.alter_column('space', 'domain',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=64),
               comment='空间域名,也用于标识访问(可选,个人类型可不传入domin)',
               existing_comment='空间域名,也用于标识访问',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('space', 'domain',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=64),
               comment='空间域名,也用于标识访问',
               existing_comment='空间域名,也用于标识访问(可选,个人类型可不传入domin)',
               existing_nullable=True)
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    # ### end Alembic commands ###
