"""文档历史记录表外键调整

Revision ID: 64ab8214d15b
Revises: 62018c92acf7
Create Date: 2026-02-10 19:53:29.241296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ab8214d15b'
down_revision: Union[str, None] = '62018c92acf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_view_history_ibfk_1'), 'document_view_history', type_='foreignkey')
    op.create_foreign_key(None, 'permission_groups', 'collaborator', ['collaborator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission_groups', type_='foreignkey')
    op.create_foreign_key(op.f('document_view_history_ibfk_1'), 'document_view_history', 'document_base', ['document_id'], ['id'])
    # ### end Alembic commands ###
