"""调整空间类型字段

Revision ID: 6c40e3591b43
Revises: e5a743231c72
Create Date: 2026-09-25 14:17:17.606838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6c40e3591b43"
down_revision: Union[str, None] = "e5a743231c72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "space",
        "type",
        existing_type=mysql.ENUM("PERSONAL", "TEAM"),
        type_=sa.String(length=20),
        existing_comment="空间类型",
        existing_nullable=False,
    )
    op.alter_column(
        "space",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        comment="空间描述",
        existing_nullable=True,
    )
    conn.execute(sa.text("UPDATE space SET type = 'personal' WHERE type = 'PERSONAL'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "space",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        comment=None,
        existing_comment="空间描述",
        existing_nullable=True,
    )
    op.alter_column(
        "space",
        "type",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM("PERSONAL", "TEAM"),
        existing_comment="空间类型",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
