"""增加知识库分组表

Revision ID: 6f0d8b9a19e6
Revises: c82e405e3a65
Create Date: 2025-11-19 09:49:46.072567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0d8b9a19e6'
down_revision: Union[str, None] = 'c82e405e3a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_groups',
    sa.Column('id', sa.Integer(), nullable=False, comment='分组ID'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='用户ID'),
    sa.Column('group_name', sa.String(length=255), nullable=True, comment='分组名称'),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='排序索引'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认分组'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('display_config', sa.JSON(), nullable=True, comment='显示配置'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_groups_group_name'), 'knowledge_groups', ['group_name'], unique=False)
    op.create_index(op.f('ix_knowledge_groups_id'), 'knowledge_groups', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_groups_user_id'), 'knowledge_groups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_groups_user_id'), table_name='knowledge_groups')
    op.drop_index(op.f('ix_knowledge_groups_id'), table_name='knowledge_groups')
    op.drop_index(op.f('ix_knowledge_groups_group_name'), table_name='knowledge_groups')
    op.drop_table('knowledge_groups')
    # ### end Alembic commands ###
