"""同步协同人员模型,创建关联user

Revision ID: 7368c3a79257
Revises: 15b23446847b
Create Date: 2026-01-04 19:32:46.850424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7368c3a79257'
down_revision: Union[str, None] = '15b23446847b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'knowledge_collaborator', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_collaborator', type_='foreignkey')
    # ### end Alembic commands ###
