"""消息表结构调整

Revision ID: 7b2be82ec7ea
Revises: df029eb79353
Create Date: 2026-04-07 17:56:18.470699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2be82ec7ea'
down_revision: Union[str, None] = 'df029eb79353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('answer_group_id', sa.String(length=36), nullable=True, comment='答案组id'))
    op.add_column('chat_message', sa.Column('version', sa.Integer(), nullable=True, comment='版本'))
    op.create_unique_constraint('uniq_answer_group_id_id_version', 'chat_message', ['answer_group_id', 'id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_answer_group_id_id_version', 'chat_message', type_='unique')
    op.drop_column('chat_message', 'version')
    op.drop_column('chat_message', 'answer_group_id')
    # ### end Alembic commands ###
