"""去除知识库base表的group_id外键

Revision ID: 7c28ef448f94
Revises: 4528918fc7c5
Create Date: 2026-06-18 11:43:30.482360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c28ef448f94'
down_revision: Union[str, None] = '4528918fc7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('knowledge_base_ibfk_1'), 'knowledge_base', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_base_group_id'), table_name='knowledge_base')
    op.drop_column('knowledge_base', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('group_id', mysql.VARCHAR(length=36), nullable=False, comment='所属分组'))
    op.create_foreign_key(op.f('knowledge_base_ibfk_1'), 'knowledge_base', 'knowledge_group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_knowledge_base_group_id'), 'knowledge_base', ['group_id'], unique=False)
    # ### end Alembic commands ###
