"""添加编辑和浏览记录表,混入deleted_at用于软删除

Revision ID: 7dc49ca1ce94
Revises: cc0c736dec15
Create Date: 2026-01-14 14:27:41.079887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc49ca1ce94'
down_revision: Union[str, None] = 'cc0c736dec15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_edit_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uniq_document_id_user_id')
    )
    op.create_index('idx_document_id', 'document_edit_history', ['document_id'], unique=False)
    op.create_index('idx_user_id', 'document_edit_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_edit_history_document_id'), 'document_edit_history', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_edit_history_user_id'), 'document_edit_history', ['user_id'], unique=False)
    op.create_table('document_view_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('viewed_all_count_for_user', sa.Integer(), nullable=False, comment='用户浏览了该文档的总次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uniq_document_id_user_id')
    )
    op.create_index('idx_document_id', 'document_view_history', ['document_id'], unique=False)
    op.create_index('idx_user_id', 'document_view_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_view_history_document_id'), 'document_view_history', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_view_history_user_id'), 'document_view_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_view_history_viewed_all_count_for_user'), 'document_view_history', ['viewed_all_count_for_user'], unique=False)
    op.add_column('document_base', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.add_column('document_node', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.add_column('knowledge_base', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.add_column('knowledge_group', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_group', 'deleted_at')
    op.drop_column('knowledge_base', 'deleted_at')
    op.drop_column('document_node', 'deleted_at')
    op.drop_column('document_base', 'deleted_at')
    op.drop_index(op.f('ix_document_view_history_viewed_all_count_for_user'), table_name='document_view_history')
    op.drop_index(op.f('ix_document_view_history_user_id'), table_name='document_view_history')
    op.drop_index(op.f('ix_document_view_history_document_id'), table_name='document_view_history')
    op.drop_index('idx_user_id', table_name='document_view_history')
    op.drop_index('idx_document_id', table_name='document_view_history')
    op.drop_table('document_view_history')
    op.drop_index(op.f('ix_document_edit_history_user_id'), table_name='document_edit_history')
    op.drop_index(op.f('ix_document_edit_history_document_id'), table_name='document_edit_history')
    op.drop_index('idx_user_id', table_name='document_edit_history')
    op.drop_index('idx_document_id', table_name='document_edit_history')
    op.drop_table('document_edit_history')
    # ### end Alembic commands ###
