"""同步生成附件表

Revision ID: 83b310681c38
Revises: b52010830d7e
Create Date: 2025-11-19 18:35:08.334629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b310681c38'
down_revision: Union[str, None] = 'b52010830d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='附件名称'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='附件类型'),
    sa.Column('object_name', sa.String(length=255), nullable=False, comment='文件的唯一标识路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='附件大小'),
    sa.Column('bucket_name', sa.String(length=255), nullable=False, comment='bucket名'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_file_name'), 'attachment', ['file_name'], unique=False)
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=False)
    op.create_index(op.f('ix_attachment_user_id'), 'attachment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_user_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_file_name'), table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
