"""调整通知表的字段

Revision ID: 85ad41fce17a
Revises: 07211956930e
Create Date: 2026-04-20 10:22:52.102032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85ad41fce17a'
down_revision: Union[str, None] = '07211956930e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notification_ibfk_1'), 'notification', type_='foreignkey')
    op.drop_index(op.f('uix_user_id_biz_type_biz_id'), table_name='notification')
    op.create_index('idx_mentioned_user_id_created_at', 'notification', ['mentioned_user_id', 'created_at'], unique=False)
    op.create_index('idx_mentioned_user_id_read_at', 'notification', ['mentioned_user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notification_actor_user_id'), 'notification', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_notification_mentioned_user_id'), 'notification', ['mentioned_user_id'], unique=False)
    op.create_unique_constraint('uix_mentioned_user_id_biz_type_biz_id', 'notification', ['mentioned_user_id', 'biz_type', 'biz_id'])
    op.create_foreign_key(None, 'notification', 'user', ['actor_user_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'user', ['mentioned_user_id'], ['id'])
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='用户id'))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_ibfk_1'), 'notification', 'user', ['user_id'], ['id'])
    op.drop_constraint('uix_mentioned_user_id_biz_type_biz_id', 'notification', type_='unique')
    op.drop_index(op.f('ix_notification_mentioned_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_actor_user_id'), table_name='notification')
    op.drop_index('idx_mentioned_user_id_read_at', table_name='notification')
    op.drop_index('idx_mentioned_user_id_created_at', table_name='notification')
    op.create_index(op.f('uix_user_id_biz_type_biz_id'), 'notification', ['user_id', 'biz_type', 'biz_id'], unique=True)
    # ### end Alembic commands ###
