"""修改文档模型,增加外键

Revision ID: 9582d8948fec
Revises: 0a8ce53073fd
Create Date: 2026-01-15 15:57:29.756369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9582d8948fec'
down_revision: Union[str, None] = '0a8ce53073fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_base', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_view_history', 'user', ['viewed_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_view_history', type_='foreignkey')
    op.drop_constraint(None, 'document_base', type_='foreignkey')
    # ### end Alembic commands ###
