"""新增常用知识库pin表

Revision ID: 981f9480e6ef
Revises: ab2184a104fa
Create Date: 2026-06-16 15:23:58.512068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981f9480e6ef'
down_revision: Union[str, None] = 'ab2184a104fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_common_pin',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('knowledge_id', sa.String(length=36), nullable=True, comment='知识库ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('order_index', sa.Integer(), nullable=True, comment='排序索引'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_id', name='uix_user_knowledge')
    )
    op.create_index(op.f('ix_knowledge_common_pin_id'), 'knowledge_common_pin', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_common_pin_knowledge_id'), 'knowledge_common_pin', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_knowledge_common_pin_user_id'), 'knowledge_common_pin', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_common_pin_user_id'), table_name='knowledge_common_pin')
    op.drop_index(op.f('ix_knowledge_common_pin_knowledge_id'), table_name='knowledge_common_pin')
    op.drop_index(op.f('ix_knowledge_common_pin_id'), table_name='knowledge_common_pin')
    op.drop_table('knowledge_common_pin')
    # ### end Alembic commands ###
