"""同步协同者相关model

Revision ID: 9c74ee41b8ab
Revises: 56b658751814
Create Date: 2025-12-18 11:13:31.472373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c74ee41b8ab'
down_revision: Union[str, None] = '56b658751814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_collaborator',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('knowledge_id', sa.String(length=36), nullable=False, comment='所属知识库'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('role', sa.String(length=10), nullable=False, comment='角色'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态'),
    sa.Column('source', sa.Integer(), nullable=False, comment='来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_collaborator_id'), 'knowledge_collaborator', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_collaborator_knowledge_id'), 'knowledge_collaborator', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_knowledge_collaborator_user_id'), 'knowledge_collaborator', ['user_id'], unique=False)
    op.create_table('knowledge_invitation',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('knowledge_id', sa.String(length=36), nullable=False, comment='所属知识库'),
    sa.Column('inviter_id', sa.Integer(), nullable=True, comment='被邀请用户id'),
    sa.Column('token', sa.String(length=45), nullable=False, comment='邀请链接token'),
    sa.Column('role', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('need_approval', sa.Integer(), nullable=True, comment='是否需要审批:0-否,1-是'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态:1-正常,2-已撤销'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_knowledge_invitation_id'), 'knowledge_invitation', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_invitation_inviter_id'), 'knowledge_invitation', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_knowledge_invitation_knowledge_id'), 'knowledge_invitation', ['knowledge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_invitation_knowledge_id'), table_name='knowledge_invitation')
    op.drop_index(op.f('ix_knowledge_invitation_inviter_id'), table_name='knowledge_invitation')
    op.drop_index(op.f('ix_knowledge_invitation_id'), table_name='knowledge_invitation')
    op.drop_table('knowledge_invitation')
    op.drop_index(op.f('ix_knowledge_collaborator_user_id'), table_name='knowledge_collaborator')
    op.drop_index(op.f('ix_knowledge_collaborator_knowledge_id'), table_name='knowledge_collaborator')
    op.drop_index(op.f('ix_knowledge_collaborator_id'), table_name='knowledge_collaborator')
    op.drop_table('knowledge_collaborator')
    # ### end Alembic commands ###
