"""调整通知表部分字段

Revision ID: 9e90556dfca4
Revises: dd50996b0695
Create Date: 2026-04-22 18:00:39.741330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e90556dfca4'
down_revision: Union[str, None] = 'dd50996b0695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 兼容历史数据
    op.execute('UPDATE notification SET list_type = "mention_or_comment" WHERE list_type IS NULL')
    op.alter_column('notification', 'list_type', existing_type=sa.String(length=20), nullable=False)
    op.drop_column('notification', 'content')
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', mysql.VARCHAR(length=255), nullable=False, comment='标题'))
    op.add_column('notification', sa.Column('content', mysql.TEXT(), nullable=True, comment='内容'))
    op.drop_column('notification', 'list_type')
    # ### end Alembic commands ###
