"""外键删除

Revision ID: a5d2bbda09b7
Revises: 45b6ed0a98f6
Create Date: 2026-01-14 20:42:40.834167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d2bbda09b7'
down_revision: Union[str, None] = '45b6ed0a98f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_node_ibfk_3'), 'document_node', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('document_node_ibfk_3'), 'document_node', 'knowledge_base', ['knowledge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
