"""创建mq同步表

Revision ID: aa73993d052d
Revises: c912439146a8
Create Date: 2026-03-18 18:22:05.952921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa73993d052d'
down_revision: Union[str, None] = 'c912439146a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_sync',
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='文档ID(这里用于主键)'),
    sa.Column('last_content_updated_at', mysql.DATETIME(fsp=3), nullable=False, comment='最后一次内容更新时间'),
    sa.Column('next_run_at', mysql.DATETIME(fsp=3), nullable=False, comment='下次运行时间(定时任务调度)'),
    sa.Column('locked_at', mysql.DATETIME(fsp=3), nullable=True, comment='锁定时间'),
    sa.Column('lock_token', sa.String(length=36), nullable=True, comment='锁定令牌'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_vector_sync_document_id'), 'vector_sync', ['document_id'], unique=False)
    op.create_index(op.f('ix_vector_sync_next_run_at'), 'vector_sync', ['next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_sync_next_run_at'), table_name='vector_sync')
    op.drop_index(op.f('ix_vector_sync_document_id'), table_name='vector_sync')
    op.drop_table('vector_sync')
    # ### end Alembic commands ###
