"""调整邀请表相关字段

Revision ID: ab2184a104fa
Revises: 9e90556dfca4
Create Date: 2026-04-28 14:46:23.464073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab2184a104fa'
down_revision: Union[str, None] = '9e90556dfca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('invitate_user_id', sa.Integer(), nullable=False, comment='邀请人（发起邀请的人）'))
    op.drop_index(op.f('ix_invitation_inviter_id'), table_name='invitation')
    op.create_index(op.f('ix_invitation_invitate_user_id'), 'invitation', ['invitate_user_id'], unique=False)
    op.drop_column('invitation', 'inviter_id')
    op.alter_column('notification', 'list_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='列表类型(用于分组展示)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'list_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='列表类型(用于分组展示)',
               existing_nullable=False)
    op.add_column('invitation', sa.Column('inviter_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='被邀请用户id'))
    op.drop_index(op.f('ix_invitation_invitate_user_id'), table_name='invitation')
    op.create_index(op.f('ix_invitation_inviter_id'), 'invitation', ['inviter_id'], unique=False)
    op.drop_column('invitation', 'invitate_user_id')
    # ### end Alembic commands ###
