"""调整知识库icon字段

Revision ID: b1714a76f3de
Revises: 098c6380dd8d
Create Date: 2025-11-21 20:07:46.730632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1714a76f3de'
down_revision: Union[str, None] = '098c6380dd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'icon',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               comment='知识库图标')
    op.alter_column('knowledge_base', 'slug',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False,
               existing_comment='知识库短链')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'slug',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True,
               existing_comment='知识库短链')
    op.alter_column('knowledge_base', 'icon',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='知识库图标')
    # ### end Alembic commands ###
