"""调整userId的类型

Revision ID: b52010830d7e
Revises: 3a938e67471c
Create Date: 2025-11-19 11:27:05.686291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b52010830d7e'
down_revision: Union[str, None] = '3a938e67471c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='所属用户',
               existing_nullable=False)
    op.alter_column('knowledge_group', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_group', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='用户ID',
               existing_nullable=True)
    op.alter_column('knowledge_base', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='所属用户',
               existing_nullable=False)
    # ### end Alembic commands ###
