"""mq同步表增加知识库id

Revision ID: bda97ce03d8d
Revises: aa73993d052d
Create Date: 2026-03-18 18:47:06.259836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda97ce03d8d'
down_revision: Union[str, None] = 'aa73993d052d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_sync', sa.Column('knowledge_id', sa.String(length=36), nullable=True, comment='所属知识库ID'))
    op.create_index(op.f('ix_vector_sync_knowledge_id'), 'vector_sync', ['knowledge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_sync_knowledge_id'), table_name='vector_sync')
    op.drop_column('vector_sync', 'knowledge_id')
    # ### end Alembic commands ###
