"""创建知识库日统计表

Revision ID: c113f7f65ca4
Revises: c709cdb31a7d
Create Date: 2026-01-08 17:39:26.737605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c113f7f65ca4'
down_revision: Union[str, None] = 'c709cdb31a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_daily_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_id', sa.String(length=36), nullable=False),
    sa.Column('stats_date', sa.DateTime(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_id', 'stats_date', name='uix_knowledge_id_stats_date')
    )
    op.create_index('idx_knowledge_id', 'knowledge_daily_stats', ['knowledge_id'], unique=False)
    op.create_index('idx_stats_date', 'knowledge_daily_stats', ['stats_date'], unique=False)
    op.create_unique_constraint('uniq_knowledge_id_document_slug', 'document_base', ['knowledge_id', 'slug'])
    op.create_unique_constraint('uniq_knowledge_slug', 'knowledge_base', ['slug'])
    op.drop_column('knowledge_base', 'items_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('items_count', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='文档数量'))
    op.drop_constraint('uniq_knowledge_slug', 'knowledge_base', type_='unique')
    op.drop_constraint('uniq_knowledge_id_document_slug', 'document_base', type_='unique')
    op.drop_index('idx_stats_date', table_name='knowledge_daily_stats')
    op.drop_index('idx_knowledge_id', table_name='knowledge_daily_stats')
    op.drop_table('knowledge_daily_stats')
    # ### end Alembic commands ###
