"""增加node_json字段

Revision ID: c709cdb31a7d
Revises: e8114ef64dee
Create Date: 2026-01-07 17:24:46.856446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c709cdb31a7d'
down_revision: Union[str, None] = 'e8114ef64dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_content', sa.Column('node_json', sa.Text(), nullable=False, comment='文档内容(为协同编辑的的二进制json数据)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_content', 'node_json')
    # ### end Alembic commands ###
