"""change_knowledge_id_to_uuid

Revision ID: c82e405e3a65
Revises: 
Create Date: 2025-11-17 11:26:22.462744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c82e405e3a65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.add_column('knowledge_base', sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属分组'))
    op.alter_column('knowledge_base', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.String(length=36),
               existing_comment='主键',
               existing_nullable=False)
    op.drop_index('idx_knowledge_user', table_name='knowledge_base')
    op.create_index(op.f('ix_knowledge_base_group_id'), 'knowledge_base', ['group_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_user_id'), 'knowledge_base', ['user_id'], unique=False)
    op.drop_table_comment(
        'knowledge_base',
        existing_comment='知识库',
        schema=None
    )
    op.drop_column('knowledge_base', 'enable_auto_publish')
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='用户名,用于登录',
               existing_nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='昵称,可重复不唯一',
               existing_nullable=True)
    op.drop_index('username', table_name='users')
    op.drop_index('username_2', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('username_2', 'users', ['username'], unique=True)
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment='昵称,可重复不唯一',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               comment='用户名,用于登录',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('knowledge_base', sa.Column('enable_auto_publish', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否自动发布'))
    op.create_table_comment(
        'knowledge_base',
        '知识库',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_knowledge_base_user_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_group_id'), table_name='knowledge_base')
    op.create_index('idx_knowledge_user', 'knowledge_base', ['user_id'], unique=False)
    op.alter_column('knowledge_base', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='主键',
               existing_nullable=False)
    op.drop_column('knowledge_base', 'group_id')
    op.create_table('documents',
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', mysql.LONGBLOB(), nullable=False),
    sa.Column('update_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
