"""新增消息表字段

Revision ID: c84d2a70587d
Revises: fb4d83937fbb
Create Date: 2026-04-03 17:42:10.392864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84d2a70587d'
down_revision: Union[str, None] = 'fb4d83937fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('link_question', sa.String(length=255), nullable=True, comment='关联问题(用于重新生成答案)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'link_question')
    # ### end Alembic commands ###
