"""外键增加联动删除

Revision ID: c912439146a8
Revises: 64ab8214d15b
Create Date: 2026-02-10 20:07:36.017067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c912439146a8'
down_revision: Union[str, None] = '64ab8214d15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_edit_history_ibfk_1'), 'document_edit_history', type_='foreignkey')
    op.create_foreign_key(None, 'document_edit_history', 'document_base', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_view_history', 'document_base', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_view_history', type_='foreignkey')
    op.drop_constraint(None, 'document_edit_history', type_='foreignkey')
    op.create_foreign_key(op.f('document_edit_history_ibfk_1'), 'document_edit_history', 'document_base', ['document_id'], ['id'])
    # ### end Alembic commands ###
