"""调整filetype长度

Revision ID: cc0c736dec15
Revises: 2eba7055c978
Create Date: 2026-01-13 11:06:10.366990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc0c736dec15'
down_revision: Union[str, None] = '2eba7055c978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'file_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_comment='附件类型',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'file_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               existing_comment='附件类型',
               existing_nullable=True)
    # ### end Alembic commands ###
