"""同步model到数据库

Revision ID: cf85bfd43b0e
Revises: 62018c92acf7
Create Date: 2026-02-05 18:46:44.506401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf85bfd43b0e'
down_revision: Union[str, None] = '62018c92acf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限组名称'),
    sa.Column('role', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('target_type', sa.String(length=30), nullable=False, comment='目标类型(knowledge/document)'),
    sa.Column('target_id', sa.String(length=36), nullable=False, comment='目标ID(知识库/文档ID)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_abilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('permission_group_id', sa.String(length=36), nullable=False, comment='权限组ID'),
    sa.Column('ability_key', sa.String(length=30), nullable=False, comment='能力键'),
    sa.Column('enable', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('knowledge_collaborator_backup')
    op.add_column('collaborator', sa.Column('permission_group_id', sa.String(length=36), nullable=False, comment='权限组ID'))
    op.alter_column('collaborator', 'document_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='所属文档',
               existing_nullable=True)
    op.alter_column('collaborator', 'target_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Integer(),
               comment='目标类型:知识库/文档',
               existing_comment="目标类型：'knowledge'-知识库;'document'-文档",
               existing_nullable=False)
    op.create_index(op.f('ix_collaborator_document_id'), 'collaborator', ['document_id'], unique=False)
    op.create_foreign_key(None, 'collaborator', 'document_base', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collaborator', 'permission_groups', ['permission_group_id'], ['id'])
    op.alter_column('invitation', 'invitate_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='邀请来源:knowledge-知识库,document-文档',
               existing_comment="邀请类型：'knowledge'-知识库；'document'-文档",
               existing_nullable=False)
    op.create_index(op.f('ix_invitation_document_id'), 'invitation', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_document_id'), table_name='invitation')
    op.alter_column('invitation', 'invitate_type',
               existing_type=mysql.VARCHAR(length=20),
               comment="邀请类型：'knowledge'-知识库；'document'-文档",
               existing_comment='邀请来源:knowledge-知识库,document-文档',
               existing_nullable=False)
    op.drop_constraint(None, 'collaborator', type_='foreignkey')
    op.drop_constraint(None, 'collaborator', type_='foreignkey')
    op.drop_index(op.f('ix_collaborator_document_id'), table_name='collaborator')
    op.alter_column('collaborator', 'target_type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=20),
               comment="目标类型：'knowledge'-知识库;'document'-文档",
               existing_comment='目标类型:知识库/文档',
               existing_nullable=False)
    op.alter_column('collaborator', 'document_id',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='所属文档',
               existing_nullable=True)
    op.drop_column('collaborator', 'permission_group_id')
    op.create_table('knowledge_collaborator_backup',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False, comment='主键'),
    sa.Column('knowledge_id', mysql.VARCHAR(length=36), nullable=False, comment='所属知识库'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属用户'),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False, comment='角色'),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False, comment='状态'),
    sa.Column('source', mysql.INTEGER(), autoincrement=False, nullable=False, comment='来源'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('permission_abilities')
    op.drop_table('permission_groups')
    # ### end Alembic commands ###
