"""调整通知表bizid字段长度

Revision ID: dd50996b0695
Revises: 85ad41fce17a
Create Date: 2026-04-20 18:48:20.578030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd50996b0695'
down_revision: Union[str, None] = '85ad41fce17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'biz_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=128),
               existing_comment='业务id(用于幂等性)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'biz_id',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=36),
               existing_comment='业务id(用于幂等性)',
               existing_nullable=True)
    # ### end Alembic commands ###
