"""还原chat_message表的字段,不存版本信息了

Revision ID: ddb9017b3d46
Revises: c84d2a70587d
Create Date: 2026-04-08 12:11:00.044584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ddb9017b3d46'
down_revision: Union[str, None] = 'c84d2a70587d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uniq_answer_group_id_id_version'), table_name='chat_message')
    op.drop_column('chat_message', 'answer_group_id')
    op.drop_column('chat_message', 'context_json')
    op.drop_column('chat_message', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=True, comment='版本'))
    op.add_column('chat_message', sa.Column('context_json', mysql.JSON(), nullable=True, comment='上下文json(用于缓存一些替换的上下文)'))
    op.add_column('chat_message', sa.Column('answer_group_id', mysql.VARCHAR(length=36), nullable=True, comment='答案组id'))
    op.create_index(op.f('uniq_answer_group_id_id_version'), 'chat_message', ['answer_group_id', 'id', 'version'], unique=True)
    # ### end Alembic commands ###
