"""消息表增加上下文json

Revision ID: df029eb79353
Revises: c84d2a70587d
Create Date: 2026-04-07 10:15:19.066571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df029eb79353'
down_revision: Union[str, None] = 'c84d2a70587d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('context_json', sa.JSON(), nullable=True, comment='上下文json(用于缓存一些替换的上下文)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'context_json')
    # ### end Alembic commands ###
