"""增加view_count字段

Revision ID: e8114ef64dee
Revises: 7368c3a79257
Create Date: 2026-01-07 09:30:30.279217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8114ef64dee'
down_revision: Union[str, None] = '7368c3a79257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_base', sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览次数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_base', 'view_count')
    # ### end Alembic commands ###
