"""新增消息意见字段

Revision ID: e8b48d3b44a9
Revises: ddb9017b3d46
Create Date: 2026-04-08 17:06:40.319825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b48d3b44a9'
down_revision: Union[str, None] = 'ddb9017b3d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('suggestions', sa.JSON(), nullable=True, comment='建议列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'suggestions')
    # ### end Alembic commands ###
