"""增加知识库外键约束

Revision ID: f6a116a4b903
Revises: 6f0d8b9a19e6
Create Date: 2025-11-19 10:37:15.974817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6a116a4b903'
down_revision: Union[str, None] = '6f0d8b9a19e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'group_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_comment='所属分组',
               existing_nullable=False)
    op.create_foreign_key(None, 'knowledge_base', 'knowledge_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.alter_column('knowledge_base', 'group_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_comment='所属分组',
               existing_nullable=False)
    # ### end Alembic commands ###
