"""对比表结构差异

Revision ID: f822d36228fa
Revises: 
Create Date: 2025-11-14 15:26:57.018466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f822d36228fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.add_column('knowledge_base', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('knowledge_base', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('knowledge_base', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.alter_column('knowledge_base', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('knowledge_base', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='所属用户',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_knowledge_user', table_name='knowledge_base')
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_user_id'), 'knowledge_base', ['user_id'], unique=True)
    op.create_index(op.f('ix_knowledge_base_username'), 'knowledge_base', ['username'], unique=True)
    op.drop_table_comment(
        'knowledge_base',
        existing_comment='知识库',
        schema=None
    )
    op.drop_column('knowledge_base', 'description')
    op.drop_column('knowledge_base', 'content_updated_at')
    op.drop_column('knowledge_base', 'slug')
    op.drop_column('knowledge_base', 'enable_auto_publish')
    op.drop_column('knowledge_base', 'is_public')
    op.drop_column('knowledge_base', 'name')
    op.drop_column('knowledge_base', 'cover_url')
    op.drop_column('knowledge_base', 'items_count')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='用户名,用于登录',
               existing_nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='昵称,可重复不唯一',
               existing_nullable=True)
    op.drop_index('username', table_name='users')
    op.drop_index('username_2', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('username_2', 'users', ['username'], unique=True)
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment='昵称,可重复不唯一',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               comment='用户名,用于登录',
               existing_nullable=False)
    op.add_column('knowledge_base', sa.Column('items_count', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='文档数量'))
    op.add_column('knowledge_base', sa.Column('cover_url', mysql.VARCHAR(length=255), nullable=True, comment='封面图'))
    op.add_column('knowledge_base', sa.Column('name', mysql.VARCHAR(length=128), nullable=False, comment='知识库名称'))
    op.add_column('knowledge_base', sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否公开'))
    op.add_column('knowledge_base', sa.Column('enable_auto_publish', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否自动发布'))
    op.add_column('knowledge_base', sa.Column('slug', mysql.VARCHAR(length=64), nullable=True, comment='知识库短链'))
    op.add_column('knowledge_base', sa.Column('content_updated_at', mysql.DATETIME(), nullable=True, comment='内容最近更新时间'))
    op.add_column('knowledge_base', sa.Column('description', mysql.VARCHAR(length=512), nullable=True, comment='简介'))
    op.create_table_comment(
        'knowledge_base',
        '知识库',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_knowledge_base_username'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_user_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.create_index('idx_knowledge_user', 'knowledge_base', ['user_id'], unique=False)
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'user_id',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(unsigned=True),
               comment='所属用户',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('knowledge_base', 'nickname')
    op.drop_column('knowledge_base', 'password')
    op.drop_column('knowledge_base', 'username')
    op.create_table('documents',
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', mysql.LONGBLOB(), nullable=False),
    sa.Column('update_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
