"""v2 数据迁移-增加一些授权表

Revision ID: f85b5aac6c6e
Revises: 5984b406803c
Create Date: 2026-09-07 18:51:58.050578
说明： 仅增加新表，不删除旧列，不做数据回填
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f85b5aac6c6e"
down_revision: Union[str, None] = "5984b406803c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_grant",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "resource_type",
            sa.String(length=30),
            nullable=False,
            comment="资源类型,knowledge:知识库,document:文档",
        ),
        sa.Column(
            "resource_id", sa.String(length=36), nullable=False, comment="资源ID"
        ),
        sa.Column(
            "principal_type",
            sa.String(length=30),
            nullable=False,
            comment="主体类型,user:用户,space_role:空间角色,team_role:团队角色",
        ),
        sa.Column(
            "principal_id", sa.String(length=36), nullable=False, comment="主体ID"
        ),
        sa.Column(
            "principal_role",
            sa.String(length=30),
            nullable=False,
            comment="用户在空间或团队中的身份(这里是一个不固定的角色)",
        ),
        sa.Column(
            "resource_role",
            sa.String(length=30),
            nullable=False,
            comment="这个主体对知识库有什么权限",
        ),
        sa.Column(
            "source",
            sa.String(length=30),
            nullable=False,
            comment="授权来源,creator:创建者,default_policy:默认策略,direct:直接授权,invitation:邀请",
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="授权操作人"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type",
            "resource_id",
            "principal_type",
            "principal_id",
            "principal_role",
            name="uniq_resource_grant",
        ),
    )
    op.create_index(
        "idx_resource_grant_resource",
        "resource_grant",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "resource_invitation",
        sa.Column("id", sa.String(length=36), nullable=False, comment="主键"),
        sa.Column(
            "resource_id", sa.String(length=36), nullable=False, comment="资源ID"
        ),
        sa.Column(
            "resource_type",
            sa.String(length=20),
            nullable=False,
            comment="资源类型:knowledge-知识库,document-文档",
        ),
        sa.Column("inviter_id", sa.Integer(), nullable=False, comment="邀请链接创建人"),
        sa.Column(
            "token", sa.String(length=64), nullable=False, comment="邀请链接token"
        ),
        sa.Column(
            "need_approval",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
            comment="是否需要审批",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
            comment="邀请状态:active-正常,revoked-已撤销",
        ),
        sa.Column(
            "offered_role",
            sa.String(length=30),
            server_default="read",
            nullable=False,
            comment="邀请角色:read-只读,edit-可编辑,admin-管理员",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(["inviter_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type", "resource_id", name="uq_resource_invitation_resource"
        ),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_resource_invitation_id"), "resource_invitation", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_resource_invitation_inviter_id"),
        "resource_invitation",
        ["inviter_id"],
        unique=False,
    )
    op.create_table(
        "resource_access_request",
        sa.Column("id", sa.String(length=36), nullable=False, comment="主键"),
        sa.Column(
            "pending_key",
            sa.String(length=128),
            nullable=True,
            comment="待审批幂等键：仅pending状态时有值，审批结束后置空",
        ),
        sa.Column(
            "resource_type", sa.String(length=30), nullable=False, comment="资源类型"
        ),
        sa.Column(
            "resource_id", sa.String(length=36), nullable=False, comment="资源ID"
        ),
        sa.Column(
            "requested_role",
            sa.String(length=30),
            nullable=False,
            comment="请求申请的角色",
        ),
        sa.Column("applicant_user_id", sa.Integer(), nullable=False, comment="用户ID"),
        sa.Column(
            "invitation_id", sa.String(length=36), nullable=True, comment="邀请ID"
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="状态",
        ),
        sa.Column("reviewed_by", sa.Integer(), nullable=True, comment="审核用户ID"),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True, comment="审核时间"),
        sa.Column(
            "apply_message", sa.String(length=255), nullable=True, comment="申请说明"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
            comment="申请时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["applicant_user_id"], ["user.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"], ["resource_invitation.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pending_key", name="uq_resource_access_request_pending_key"
        ),
    )
    op.create_index(
        "idx_access_request_applicant_resource",
        "resource_access_request",
        ["applicant_user_id", "resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "idx_access_request_resource_status",
        "resource_access_request",
        ["resource_type", "resource_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_access_request_applicant_user_id"),
        "resource_access_request",
        ["applicant_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_access_request_id"),
        "resource_access_request",
        ["id"],
        unique=False,
    )
    #  visibility,保留is_public
    op.add_column(
        "knowledge_base",
        sa.Column(
            "visibility",
            sa.String(length=20),
            server_default=sa.text("'private'"),
            nullable=False,
            comment="公开范围: private私有, space空间成员可见, public互联网公开",
        ),
    )
    op.add_column(
        "document_base",
        sa.Column(
            "visibility",
            sa.String(length=20),
            server_default=sa.text("'inherit'"),
            nullable=False,
            comment="文档可见类别: inherit(继承知识库权限), space(空间内部成员可见),private(不继承知识库的空间/公开范围), public(互联网公开)",
        ),
    )
    op.add_column(
        "knowledge_base",
        sa.Column(
            "creator_id",
            sa.Integer(),
            nullable=True,
            comment="知识库创建者(回填自user_id)",
        ),
    )
    op.create_index(
        op.f("ix_knowledge_base_creator_id"),
        "knowledge_base",
        ["creator_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_knowledge_base_creator_id",
        "knowledge_base",
        "user",
        ["creator_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.add_column(
        "permission_groups",
        sa.Column(
            "scope_type",
            sa.String(length=30),
            nullable=True,
            comment="作用域类型：knowledge/document/space/team",
        ),
    )
    op.add_column(
        "permission_groups",
        sa.Column("scope_id", sa.String(length=36), nullable=True, comment="作用域ID"),
    )
    op.add_column(
        "permission_groups",
        sa.Column("role_key", sa.String(length=30), nullable=True, comment="资源角色"),
    )

    op.add_column(
        "permission_abilities",
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
            comment="是否启用",
        ),
    )


def downgrade() -> None:
    op.drop_column("permission_abilities", "enabled")
    op.drop_column("permission_groups", "scope_type")
    op.drop_column("permission_groups", "scope_id")
    op.drop_column("permission_groups", "role_key")
    op.drop_constraint(
        "fk_knowledge_base_creator_id", "knowledge_base", type_="foreignkey"
    )
    op.drop_index(op.f("ix_knowledge_base_creator_id"), table_name="knowledge_base")

    op.drop_column("knowledge_base", "creator_id")
    op.drop_column("knowledge_base", "visibility")
    op.drop_column("document_base", "visibility")

    op.drop_index(
        op.f("ix_resource_access_request_id"), table_name="resource_access_request"
    )
    op.drop_index(
        op.f("ix_resource_access_request_applicant_user_id"),
        table_name="resource_access_request",
    )
    op.drop_index(
        op.f("idx_access_request_resource_status"), table_name="resource_access_request"
    )
    op.drop_index(
        op.f("idx_access_request_applicant_resource"),
        table_name="resource_access_request",
    )

    op.drop_table("resource_access_request")

    op.drop_index(op.f("ix_resource_invitation_id"), table_name="resource_invitation")
    op.drop_index(
        op.f("ix_resource_invitation_inviter_id"), table_name="resource_invitation"
    )
    op.drop_table("resource_invitation")
    op.drop_index("idx_resource_grant_resource", table_name="resource_grant")
    op.drop_table("resource_grant")
