"""同步session的一些字段

Revision ID: fb4d83937fbb
Revises: 3f02410d5391
Create Date: 2026-03-26 18:30:05.406015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb4d83937fbb'
down_revision: Union[str, None] = '3f02410d5391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间(NULL表示未删除)'))
    op.alter_column('chat_session', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_comment='用户id',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_session', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_comment='用户id',
               existing_nullable=True)
    op.drop_column('chat_session', 'deleted_at')
    # ### end Alembic commands ###
