"""调整统计表插入日期字段类型

Revision ID: ff6a9c871364
Revises: c113f7f65ca4
Create Date: 2026-01-08 17:58:07.999405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff6a9c871364'
down_revision: Union[str, None] = 'c113f7f65ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_daily_stats', 'stats_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_daily_stats', 'stats_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
